"""One-off helper: derive a first-pass walkability grid from the map image.

The output (shared/src/map/collision.ts) is meant to be hand-edited afterwards,
so re-running this script overwrites manual fixes.
"""
import sys
from collections import deque
from PIL import Image, ImageDraw

CELL = 4
SRC = "assets/Scene Overview.png"
OUT = "shared/src/map/collision.ts"
SPAWN = (540, 600)  # a pixel known to be on open ground

# Stairs and passages the color heuristic marks as blocked (map pixel coords).
WALKABLE_OVERRIDES = [
    [(646, 136), (694, 136), (694, 240), (646, 240)],  # top shrine stairs
    [(392, 360), (436, 360), (436, 462), (392, 462)],  # statue terrace stairs
    [(583, 488), (630, 488), (630, 592), (583, 592)],  # center stairs
    [(807, 652), (854, 652), (854, 752), (807, 752)],  # east inner stairs
    [(327, 872), (373, 872), (373, 980), (327, 980)],  # south-west stairs
    [(752, 418), (790, 418), (790, 505), (752, 505)],  # stone arch
    [(300, 503), (212, 546), (212, 571), (300, 530)],  # west wing stairs
    [(912, 540), (1000, 578), (1000, 604), (912, 566)],  # east wing stairs
    [(750, 330), (788, 330), (788, 380), (750, 380)],  # gap in the north curb
    [(285, 965), (330, 965), (330, 995), (285, 995)],  # south-west corner link
]

im = Image.open(SRC).convert("RGB")
W, H = im.size
px = im.load()


def classify(r, g, b):
    if r - g > 25 and r < 130:
        return "outline"
    if g > b + 50 and g > 80:
        return "grass"
    if abs(r - g) < 15 and r >= 140 and b > 100:
        return "stone"
    return "blocked"


override = Image.new("L", im.size, 0)
draw = ImageDraw.Draw(override)
for poly in WALKABLE_OVERRIDES:
    draw.polygon(poly, fill=255)
ov_px = override.load()

cols, rows = W // CELL, H // CELL
walk = [[False] * cols for _ in range(rows)]
for cy in range(rows):
    for cx in range(cols):
        ok = 0
        outline = 0
        for y in range(cy * CELL, cy * CELL + CELL):
            for x in range(cx * CELL, cx * CELL + CELL):
                k = classify(*px[x, y])
                if k == "outline":
                    outline += 1
                elif k != "blocked":
                    ok += 1
        forced = ov_px[cx * CELL + CELL // 2, cy * CELL + CELL // 2] > 0
        walk[cy][cx] = forced or (outline == 0 and ok >= CELL * CELL * 0.6)

# Keep only the region connected to the spawn point.
reach = [[False] * cols for _ in range(rows)]
sx, sy = SPAWN[0] // CELL, SPAWN[1] // CELL
assert walk[sy][sx], "spawn cell is not walkable"
q = deque([(sx, sy)])
reach[sy][sx] = True
while q:
    x, y = q.popleft()
    for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
        nx, ny = x + dx, y + dy
        if 0 <= nx < cols and 0 <= ny < rows and walk[ny][nx] and not reach[ny][nx]:
            reach[ny][nx] = True
            q.append((nx, ny))

lines = ["".join("." if c else "#" for c in row) for row in reach]
with open(OUT, "w") as f:
    f.write("// Walkability grid for the map. '.' = walkable, '#' = blocked.\n")
    f.write("// First pass generated by tools/gen_collision.py, then hand-edited.\n")
    f.write(f"export const COLLISION_CELL_SIZE = {CELL};\n")
    f.write("export const COLLISION_ROWS = `\n" + "\n".join(lines) + "\n`;\n")

if len(sys.argv) > 1:
    ov = im.copy().convert("RGBA")
    layer = Image.new("RGBA", im.size, (0, 0, 0, 0))
    lp = layer.load()
    for cy in range(rows):
        for cx in range(cols):
            if reach[cy][cx]:
                for y in range(cy * CELL, cy * CELL + CELL):
                    for x in range(cx * CELL, cx * CELL + CELL):
                        lp[x, y] = (0, 120, 255, 110)
    Image.alpha_composite(ov, layer).save(sys.argv[1])
